filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    json.keys_under_root: true
    json.add_error_key: true
    multiline.pattern: '^{'
    multiline.negate: true
    multiline.match: after

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: ""
  password: ""
  index: "microservices-logs"

setup.kibana:
  host: "kibana:5601"
