filebeat.inputs:
  - type: container
    paths:
      - /var/lib/docker/containers/*/*.log
    json.keys_under_root: true
    json.add_error_key: true
    json.ignore_decoding_error: true

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "analytics-logs"

setup.kibana:
  host: "kibana:5601"
