FROM python:3.12-slim

WORKDIR /app 

COPY projects/score_service/app/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY shared /app/shared
COPY projects/score_service/app /app
COPY projects/score_service/alembic.ini /app/alembic.ini
COPY projects/score_service/alembic /app/alembic

EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]