---
apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: lde-cluster
servers: 1
agents: 0
image: docker.io/rancher/k3s:v1.30.3-k3s1

# Add a local Docker registry
registries:
  create:
    name: 'k3d-registry.localhost'
    host: '0.0.0.0'
    hostPort: '5001'

# Map external services to localhost
ports:
  - port: 80:80    # Map port 80 in the cluster to port 80 on localhost
  - port: 443:443   # Map port 443 in the cluster to port 443 on localhost
  - port: 27017:30017 # Map port 27017 in the cluster to port 27017 on localhost for MongoDB
  - port: 6379:30379  # Map port 6379 in the cluster to port 6379 on localhost for Redis
  - port: 5432:30432  # Map port 5432 in the cluster to port 5432 on localhost for PostgreSQL
  - port: 4317:30317 # Map port 4317 in the cluster to port 4317 on localhost for Opentelemetry grpc for Aspiro dashboard

